eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: laboratoires
          uri: http://localhost:8083
          predicates:
            - Path=/laboratoires/**
        - id: contacts
          uri: http://localhost:8084
          predicates:
            - Path=/contactes/**
        - id: utilisateurs
          uri: http://localhost:8085
          predicates:
            - Path=/utilisateurs/**
