eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8222
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: laboratoires
          uri: ${LABORATOIRES_URI:http://localhost:8083}
          predicates:
            - Path=/laboratoires/**
        - id: contactes
          uri: http://localhost:8084
          predicates:
            - Path=/api/contactes/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
