eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 8222
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://eureka-server:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: laboratoires
          uri: http://localhost:8083
          predicates:
            - Path=/laboratoires/**
        - id: contacts
          uri: http://localhost:8084
          predicates:
            - Path=/contactes/**
        - id: utilisateurs
          uri: http://localhost:8085
          predicates:
            - Path=/utilisateurs/**


