eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083
spring:
  application:
    name: labo-service

  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bd_gestion_labo
    username: root
    password: bissasse
  jpa:
    hibernate:
      ddl-auto: update
    database-platform:   org.hibernate.dialect.MySQL8Dialect
application:
  config:
    contacts-url: http://localhost:8084/contactes
