eureka:
  instance:
    hostname: user-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8085
spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestion_labo
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect




jwt:
  secret: ensa1234
  expiration: 86400000 # 24 heures (en millisecondes)

logging:
  level:
    org.springframework: DEBUG

