eureka:
  instance:
    hostname: labo-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083
spring:
  application:
    name: labo-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestion_labo
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform:   org.hibernate.dialect.MySQL8Dialect
application:
  config:
    contacts-url: http://localhost:8084/contactes
    user-url: http://localhost:8085/utilisateurs
