server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/configurations
