name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'
      - 'config_server/**'
      - 'discovery/**'
      - 'gateway/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create Docker network
        run: docker network create sonar_network || true

      - name: Start SonarQube service
        run: |
          docker run -d --name sonarqube --network sonar_network -p 9000:9000 -e "SONARQUBE_JDBC_URL=jdbc:h2:./sonar;DB_CLOSE_DELAY=-1;DB_FAIL_WHEN_NO_DB=FALSE" sonarqube:latest

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test Config Service
        working-directory: ./config_server
        run: mvn clean install -DskipTests=false

      - name: Build and test Discovery Service
        working-directory: ./discovery
        run: mvn clean install -DskipTests=false

      - name: Build and test Gateway Service
        working-directory: ./gateway
        run: mvn clean install -DskipTests=false

      - name: Build and test each Backend Service
        run: |
          for service in ./Backend/*/; do
            if [ -f "$service/pom.xml" ]; then
              echo "Building $service"
              cd "$service"
              mvn clean install -DskipTests=false
              mvn test
              cd - || exit
            fi
          done

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/target/surefire-reports/*.xml'

      - name: Run SonarQube Scanner
        run: |
          for service in ./Backend/*/; do
            if [ -f "$service/pom.xml" ]; then
              echo "Running SonarQube for $service"
              cd "$service"
              mvn sonar:sonar \
                -Dsonar.host.url=http://localhost:9000 \
                -Dsonar.login=sqa_d2db41815bda6347d40fa7036f75b879da1891c3
              cd - || exit
            fi
          done
