name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'
      - 'config_server/**'
      - 'discovery/**'
      - 'gateway/**'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK (choose your version, e.g., 11, 17, etc.)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build and test each module
      - name: Build and test Config Service
        working-directory: ./config_server
        run: mvn clean install -DskipTests=false

      - name: Build and test Discovery Service
        working-directory: ./discovery
        run: mvn clean install -DskipTests=false

      - name: Build and test Gateway Service
        working-directory: ./gateway
        run: mvn clean install -DskipTests=false

      - name: Build and test Backend Services
        working-directory: ./Backend
        run: |
          for service in $(ls); do
            if [ -d "$service" ] && [ "$service" != "dossiers_service" ]; then
              cd "$service"
              mvn clean install -DskipTests=false
              cd ..
            fi
          done

      # Run tests for all modules
      - name: Run tests for Backend Services (excluding `dossiers`)
        working-directory: ./Backend
        run: |
          for service in $(ls); do
            if [ -d "$service" ] && [ "$service" != "dossiers_service" ]; then
              cd "$service"
              mvn test
              cd ..
            fi
          done

      # Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/target/surefire-reports/*.xml'



